### ISSUE TITLE
class-specific custom datasets

### ISSUE THREAD

**Issue by xyzalanix** [vsitzmann/light-field-networks#1]
👋 Any pointers on how `class-specific` datasets are structured, or how they were created... or to the urls for those? atm I can't find them in the shared drive folder. Thank you!

**Comment by HaoRiziyou** [comment]
I want to reproduce the experiment of class-specific.
"python experiment_scripts/train_nmr.py --data_root=path_to_nmr_dataset"
Anyone knows which file in the google shared drive is used to be the data_root, because I unzip the file in google drive 
but it dies not work.
Error:
  File "/content/light-field-networks/hdf5_dataio.py", line 176, in get_num_instances
    return len(instances)
TypeError: object of type 'int' has no len()

**Comment by vsitzmann** [comment]
Indeed - I forgot to upload the class-specific datasets! I uploaded them now!

For the class-specific training, we use the "train_single_class.py" script - this uses the hdf5_dataio.py file, which loads the single-class hdf5 dataset files (cars_train.hdf5, for instance).

For the multi-class training, we use the "train_nmr.py" script, which uses the "multiclass_dataio.py" file. Here, the data_root should be the root directoy that you unpacked the NMR files to (plus the intrinsics.txt file from the google drive!)
